Controllers/Employee2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Model;

namespace WebApplication4.Controllers
{
    public class Employee2Controller : Controller
    {
        ApplicationDbContext dbContext = new ApplicationDbContext();

        public ActionResult Index()
        {
            var dept = dbContext.Departments.ToList();
            return View(dept);
        }

        public ActionResult EmployeeList(int id)
        {
            var emp = dbContext.Employees.Where(e => e.Department.Id == id).ToList();
            return View(emp);
        } 
        
        public ActionResult EmployeeDetails(int id)
        {
            var emp = dbContext.Employees.SingleOrDefault(e => e.Id == id);
            return View(emp);
        }
    }
}

Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Model;
namespace WebApplication4.Controllers
{
    public class EmployeeController : Controller
    {
        ApplicationDbContext dbContext = new ApplicationDbContext();
        // GET: Employee
        public ActionResult Index()
        {
            var employees = dbContext.Employees.ToList();
            return View(employees);
        }

        public ActionResult Create()
        {
            return View();
        }

        //[HttpPost]
        //public ActionResult Create(string Name, string Email, string Gender, decimal Salary, string Mobile)
        //{
        //    var emp = new Employee()
        //    {
        //        Name=Name,
        //        Email=Email,
        //        Mobile=Mobile,
        //        Gender=Gender,
        //        Salary=Salary
        //    };
        //    dbContext.Employees.Add(emp);
        //    dbContext.SaveChanges();

        //    return RedirectToAction("Index");
        //}

        [HttpPost]
        public ActionResult Create(string test)
        {

            string name=Request.Form[0];
            string email=Request.Form["Email"];
            string mobile=Request.Form["Mobile"];
            string gender=Request.Form["Gender"];
            string salary=Request.Form["Salary"];

            var emp = new Employee()
            {
                Name = name,
                Email = email,
                Mobile = mobile,
                Gender = gender,
                Salary = Convert.ToDecimal(salary)
            };
            dbContext.Employees.Add(emp);
            dbContext.SaveChanges();

            return RedirectToAction("Index");
        }


        public ActionResult Delete(int id)
        {
            var emp = dbContext.Employees.SingleOrDefault(e => e.Id == id);
            if (emp != null)
            {
                dbContext.Employees.Remove(emp);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index?error=invalid employee id");
            }
        }

        public ActionResult Edit(int? id)
        {
            var emp = dbContext.Employees.SingleOrDefault(e => e.Id == id);
            return View(emp);
        }
        [HttpPost]
        public ActionResult Edit(Employee emp)
        {
            dbContext.Entry(emp).State=System.Data.Entity.EntityState.Modified;
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication4.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Employee/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-6 offset-3">
    <div class="card">
        <div class="card-header">
            <h4>Create Employee</h4>
        </div>
        <div class="card-body">
            @using (Html.BeginForm("Create", "Employee", FormMethod.Post))
            {
                <div class="form-group">
                    <label>Employee Name</label>
                    <input type="text" class="form-control" name="Name" />
                </div>

                <div class="form-group">
                    <label>Employee Email</label>
                    <input type="text" class="form-control" name="Email" />
                </div>

                <div class="form-group">
                    <label>Employee Salary</label>
                    <input type="number" class="form-control" name="Salary" />
                </div>
                
                <div class="form-group">
                    <label>Employee Mobile</label>
                    <input type="text" class="form-control" name="Mobile" />
                </div>

                <div class="form-group">
                    <label>Employee Gender</label>
                    <select class="form-control" name="Gender">
                        <option value="">Select</option>
                        <option  value="Male">Male</option>
                        <option  value="Female">Female</option>
                    </select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Submit" class="btn btn-info" />
                </div>
            }
        </div>
    </div>
    </div>
</div>

Views/Employee/Edit.cshtml
@model WebApplication4.Model.Employee
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-6 offset-3">
        <div class="card">
            <div class="card-header">
                <h4>Edit Employee</h4>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Edit", "Employee", FormMethod.Post))
                {
                    <input type="hidden" name="Id" value="@Model.Id" />
                    <div class="form-group">
                        <label>Employee Name</label>
                        <input type="text" class="form-control" name="Name" value="@Model.Name" />
                    </div>

                    <div class="form-group">
                        <label>Employee Email</label>
                        <input type="text" class="form-control" name="Email" value="@Model.Email" />
                    </div>

                    <div class="form-group">
                        <label>Employee Salary</label>
                        <input type="number" class="form-control" name="Salary" value="@Model.Salary" />
                    </div>

                    <div class="form-group">
                        <label>Employee Mobile</label>
                        <input type="text" class="form-control" name="Mobile" value="@Model.Mobile" />
                    </div>

                    <div class="form-group">
                        <label>Employee Gender</label>
                        <select class="form-control" name="Gender" value="@Model.Gender">
                            <option value="">Select</option>
                            <option value="Male">Male</option>
                            <option value="Female">Female</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Submit" class="btn btn-info" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Views/Employee/Index.cshtml
@model IEnumerable<WebApplication4.Model.Employee>
@{
    ViewBag.Title = "Index";
}

@Html.ActionLink("Create Employee","Create","Employee")
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Email</th>
        <th>Salary</th>
        <th>Gender</th>
        <th>Action</th>
    </tr>

    @foreach (var emp in Model)
            {
                <tr>
                    <td>@emp.Id</td>
                    <td>@emp.Name</td>
                    <td>@emp.Email</td>
                    <td>@emp.Salary</td>
                    <td>@emp.Gender</td>
                    <td>
                        <a href="/Employee/Edit?id=@emp.Id"><i class="fa fa-edit"></i></a>
                        <a href="/Employee/Delete?id=@emp.Id"><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
            }
</table>

Views/Employee2/EmployeeDetails.cshtml
@model WebApplication4.Model.Employee
@{
    ViewBag.Title = "EmployeeDetails";
}

<h2>Employee Details</h2>

<div class="card">
    <div class="card-header">
        <h4 class="card-title">Employee Details</h4>
    </div>
    <div class="card-body">
        <table>
            <tr>
                <td>
                    <label>Employee Name :</label>
                </td>
                <td><label>@Model.Name</label></td>
            </tr>
            <tr>
                <td>
                    <label>Employee Email :</label>
                </td>
                <td><label>@Model.Email</label></td>
            </tr>

            <tr>
                <td>
                    <label>Employee Mobile :</label>
                </td>
                <td><label>@Model.Mobile</label></td>
            </tr>

            <tr>
                <td>
                    <label>Employee Gender :</label>
                </td>
                <td><label>@Model.Gender</label></td>
            </tr>
        </table>
    </div>
</div>

Views/Employee2/EmployeeList.cshtml
@model IEnumerable<WebApplication4.Model.Employee>
@{
    ViewBag.Title = "Index";
}

<h2>Employee List</h2>
<ul>
    @foreach (var emp in Model)
    {
        <li>
            @Html.ActionLink(emp.Name, "EmployeeDetails", "Employee2", new { id = emp.Id }, null)
        </li>
    }
</ul>
@Html.ActionLink("Back to Department","Index","Employee2")

Views/Employee2/Index.cshtml
@model IEnumerable<WebApplication4.Model.Department>
@{
    ViewBag.Title = "Index";
}

<h2>Department List</h2>
<ul>
    @foreach(var dept in Model)
            {
    <li>
        @Html.ActionLink(dept.Name, "EmployeeList", "Employee2", new { id = dept.Id }, null)
    </li>
            }
</ul>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
<link href="~/Content/bootstrap.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/Site.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-success">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>